image: gcc:latest

pipelines:
  default:
    - step:
        script:
          # Print the Linux version.
          - uname -a
          # Print the gcc version.
          - gcc --version
          #  Install a CMake 3.0.2 version.
          #- apt-get update -qq
          #- apt-get install cmake -y
          #  Alternatively you could install a CMake 3.2.2 version through PPA repository.
          - apt-get update -qq
          - apt-get install software-properties-common -y
          - apt-get install libcap-dev
          # Add PPA repository.
          - echo 'deb http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty main' | tee -a /etc/apt/sources.list.d/cmake.list
          - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 084ECFC5828AB726
          - apt-get update -qq
          - apt-get install cmake -y --force-yes
          # Print the CMake version.
          - cmake --version
          # Call the CMake.
          - cmake CMakeLists.txt
          # Build the project.
          - make
        artifacts:
          download: true
          paths:
            - bin/synaptix